export const dataList = [
  {
    name: "전자레인지, 전자레인지용 식품(편의점 냉동칸 수준)",
    point: "2",
    img: "../public/Images/",
    isChecked: false,
  },
  {
    name: "패스트푸드 프렌차이즈 음식",
    point: "4",
    img: "../public/Images/",
    isChecked: false,
  },
  {
    name: "모든 조리기구, 레시피 그리고 최상의 식재료",
    point: "6",
    img: "../public/Images/",
    isChecked: false,
  },
  {
    name: "세계 최고의 셰프가 만드는 음식이 매일 공수됨",
    point: "9",
    img: "../public/Images/",
    isChecked: false,
  },
  {
    name: "52인치짜리 TV, 모든 채널",
    point: "7",
    img: "../public/Images/",
    isChecked: false,
  },
  {
    name: "채광이 들어오는 천장",
    point: "2",
    img: "../public/Images/",
    isChecked: false,
  },
  {
    name: "당신을 사랑해주는 완벽한 이상형",
    point: "18",
    img: "../public/Images/",
    isChecked: false,
  },
  {
    name: "빔프로젝터, 지금까지의 모든 영화와 TV 프로그램(10년간 업데이트X)",
    point: "4",
    img: "../public/Images/",
    isChecked: false,
  },
  {
    name: "최고 사양으로 유지되는 PC, 온라인 게임(소통 불가능)",
    point: "",
    img: "6",
    isChecked: false,
  },
  {
    name: "최신형으로 유지되는 콘솔, 모든 콘솔 게임(업데이트O, 소통 불가능)",
    point: "4",
    img: "../public/Images/",
    isChecked: false,
  },
  {
    name: "적당한 사양의 PC, 인터넷(게임, 영화, 음악 등 컨텐츠 이용 불가능)",
    point: "16",
    img: "../public/Images/",
    isChecked: false,
  },
  {
    name: "완벽한 음향 시스템, 현존하는 모든 음반(업데이트X)",
    point: "4",
    img: "../public/Images/",
    isChecked: false,
  },
  {
    name: "웨이트 기구, 런닝머신, 농구 골대",
    point: "5",
    img: "../public/Images/",
    isChecked: false,
  },
  { name: "모든 도서(업데이트X)", point: "4", img: "", isChecked: false },
  {
    name: "일주일에 딱 하루만 작동하는 스마트폰",
    point: "4",
    img: "../public/Images/",
    isChecked: false,
  },
  {
    name: "각종 위생용품, 스파 시설",
    point: "3",
    img: "../public/Images/",
    isChecked: false,
  },
  {
    name: "죽지 않을 정도로만 치료를 제공하는 의사",
    point: "2",
    img: "../public/Images/",
    isChecked: false,
  },
  {
    name: "주기적인 건강검진과 최상의 치료를 제공하는 의사",
    point: "4",
    img: "../public/Images/",
    isChecked: false,
  },
  {
    name: "무제한 주류",
    point: "5",
    img: "../public/Images/",
    isChecked: false,
  },
  {
    name: "무제한 마약",
    point: "5",
    img: "../public/Images/",
    isChecked: false,
  },
  {
    name: "무제한 담배",
    point: "4",
    img: "../public/Images/",
    isChecked: false,
  },
  {
    name: "모든 조립완구(레고, 과학상자 등)",
    point: "2",
    img: "../public/Images/",
    isChecked: false,
  },
  {
    name: "모든 공구, 재료",
    point: "",
    img: "../public/Images/",
    isChecked: false,
  },
  { name: "당구대", point: "1", img: "../public/Images/", isChecked: false },
  {
    name: "온실 속 정원",
    point: "2",
    img: "../public/Images/",
    isChecked: false,
  },
  {
    name: "돈 미리 받고 주식투자 가능",
    point: "7",
    img: "../public/Images/",
    isChecked: false,
  },
  { name: "애완동물", point: "6", img: "../public/Images/", isChecked: false },
  {
    name: "위성 라디오",
    point: "2",
    img: "../public/Images/",
    isChecked: false,
  },
  // { name: "", point: "", img: "../public/Images/", isChecked: false },
];
